### ISSUE TITLE
download on very oft breaking connection

### ISSUE THREAD

**Issue by trivalik** [antikmozib/AM-Downloader#22]
If you have a server which breaks the download after few seconds, you are force to be in front of the PC to restart it. Try to download https://zorin.mirrors.itworxx.de/17/Zorin-OS-17.2-Education-64-bit.iso

If this works, it would be the best C# Implementation.

**Comment by antikmozib** [comment]
The most likely cause of this issue is some sort of server rule that limits the number of concurrent connections allowed from the same IP address. Consequently, the download will fail when AM Downloader is configured to use multiple connections. You can try setting _Max parallel connections per download_ to 1 in Settings and see if that solves the issue.

**Comment by trivalik** [comment]
It has nothing to do with AM Downloader. It happens also on single downloads from browser.

**Comment by antikmozib** [comment]
The operators of the server would be the place to seek help regarding this.

**Comment by trivalik** [comment]
Sorry, but more than 20 years ago, this was sometimes the only way to download files, without confirm all the time. I wonder also that this occure nowadays. This feature is what the old good "Reget Deluxe" could provide.

What's about if I would provide a pull request for it?
